[package]
name = "lib-c"
version = "0.1.0"
authors = ["Drew Pirrone-Brusse <drew.pirrone.brusse@gmail.com>"]
edition = "2018"

[features]
default = []
native = ["lib-a", "lib-a/memmap"]
wasm = []

[dependencies]
lib-a = { path = "../1_lib-a", optional = true }
