[package]
name = "exe-a"
version = "0.1.0"
authors = ["Drew Pirrone-Brusse <drew.pirrone.brusse@gmail.com>"]
edition = "2018"

[dependencies]
lib-a = { path = "../1_lib-a", default-features = false }

[build-dependencies]
lib-b = { path = "../2_lib-b" }
